spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    database-platform: ${DB_PLATFORM}
    show-sql: true
    hibernate:
      ddl-auto: ${DDL}

  datasource:
    url: jdbc:${DB}://${DB_URL}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

jwt:
  accessSecret: ${ACCESS_SECRET}
  refreshSecret: ${REFRESH_SECRET}

cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS}
      secretKey: ${S3_SECRET}
    region:
      static: ${S3_REGION}
    s3:
      bucket: ${S3_BUCKET}
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
